Repository atom/github, pull requests merged in 2018-07, with the labels that each got.

#1589 More links to .com
  lib/containers/__generated__/issueishDetailContainerQuery.graphql.js
  lib/controllers/__generated__/issueTimelineControllerQuery.graphql.js
  lib/controllers/__generated__/prTimelineControllerQuery.graphql.js
  lib/views/__generated__/issueishDetailViewRefetchQuery.graphql.js
  lib/views/issueish-detail-view.js
  lib/views/timeline-items/__generated__/commitView_item.graphql.js
  lib/views/timeline-items/__generated__/issueCommentView_item.graphql.js
  lib/views/timeline-items/commit-view.js
  lib/views/timeline-items/issue-comment-view.js
  styles/github-dotcom-markdown.less
  styles/issueish-detail-view.less
  styles/pr-timeline.less
Labels: enhancement, rfc-002

#1596 Use mocha-multi-reporters
  package-lock.json
  package.json
  test/runner.js
Labels: code-cleanup :wrench:

#1598 Split GithubTabController into twos, nay, into threes and fours
  keymaps/git.cson
  lib/containers/github-tab-container.js
  lib/controllers/github-tab-controller.js
  lib/controllers/root-controller.js
  lib/github-package.js
  lib/items/github-tab-item.js
  lib/views/git-tab-view.js
  lib/views/github-tab-view.js
  package.json
  styles/git-tab.less
  styles/github-tab.less
  styles/popover.less
  test/containers/github-tab-container.test.js
  test/controllers/git-tab-controller.test.js
  test/controllers/github-tab-controller.test.js
  test/controllers/root-controller.test.js
  test/fixtures/props/github-tab-props.js
  test/integration/launch.test.js
  test/integration/open.test.js
  test/items/github-tab-item.test.js
  test/views/github-tab-view.test.js
  test/views/remote-selector-view.test.js
Labels: code-cleanup :wrench:, work-in-progress

#1603 Rename IssueishPaneItem to IssueishDetailItem
  lib/controllers/issueish-searches-controller.js
  lib/controllers/root-controller.js
  lib/github-package.js
  lib/items/issueish-detail-item.js
  lib/views/issueish-link.js
  package.json
  test/controllers/root-controller.test.js
  test/items/issueish-detail-item.test.js
Labels: code-cleanup :wrench:

#1604 Correct integration test flake
  lib/relay-network-layer-manager.js
  lib/views/timeline-items/issue-comment-view.js
  test/integration/checkout-pr.test.js
  test/views/timeline-items/commit-view.test.js
  test/views/timeline-items/issue-comment-view.test.js
Labels: flaky-test
