Repository atom/github, pull requests merged in 2018-04, with the labels that each got.

#1374 Add dialog for new co-author
  .eslintrc
  keymaps/git.cson
  lib/controllers/commit-controller.js
  lib/controllers/git-tab-controller.js
  lib/git-shell-out-strategy.js
  lib/models/repository-states/present.js
  lib/models/repository.js
  lib/models/user-store.js
  lib/multi-list.js
  lib/relay-network-layer-manager.js
  lib/views/co-author-form.js
  lib/views/commit-view.js
  lib/views/git-tab-view.js
  styles/co-author-form.less
  styles/commit-view.less
  test/controllers/git-tab-controller.test.js
  test/helpers.js
  test/models/repository.test.js
  test/models/user-store.test.js
  test/views/co-author-form.test.js
Labels: work-in-progress

#1379 Add naming convention
  docs/naming-convention.md
Labels: documentation

#1390 React 16.3.1
  lib/containers/__generated__/prSelectionByBranchContainer_repository.graphql.js
  lib/controllers/__generated__/prInfoControllerByBranchQuery.graphql.js
  lib/controllers/git-tab-controller.js
  lib/controllers/root-controller.js
  lib/controllers/status-bar-tile-controller.js
  lib/helpers.js
  lib/models/ref-holder.js
  lib/models/repository-states/present.js
  lib/models/repository.js
  lib/views/atom-text-editor.js
  lib/views/branch-menu-view.js
  lib/views/branch-view.js
  lib/views/commit-view.js
  lib/views/decoration.js
  lib/views/dock-item.js
  lib/views/pane-item.js
  lib/views/panel.js
  lib/views/portal.js
  lib/views/push-pull-view.js
  lib/views/staging-view.js
  lib/views/status-bar.js
  lib/views/tooltip.js
  package-lock.json
  package.json
  test/controllers/commit-controller.test.js
  test/controllers/file-patch-controller.test.js
  test/controllers/git-tab-controller.test.js
  test/controllers/status-bar-tile-controller.test.js
  test/runner.js
  test/views/commit-view.test.js
  test/views/decoration.test.js
  test/views/pane-item.test.js
  test/views/panel.test.js
  test/views/portal.test.js
  test/views/staging-view.test.js
Labels: work-in-progress

#1393 🛠Replace uses of ObserveModelDecorator with ObserveModel
  lib/controllers/git-tab-controller.js
  lib/controllers/remote-pr-controller.js
  lib/controllers/repository-conflict-controller.js
  lib/controllers/root-controller.js
  lib/controllers/status-bar-tile-controller.js
  lib/decorators/observe-model.js
  lib/views/decoration.js
  lib/views/status-bar.js
  test/controllers/git-tab-controller.test.js
  test/controllers/status-bar-tile-controller.test.js
  test/decorators/observe-model.test.js
Labels: code-cleanup :wrench:

#1421 Make ListSelections immutable
  lib/models/composite-list-selection.js
  lib/models/file-patch-selection.js
  lib/models/list-selection.js
  lib/views/composite-list-selection.js
  lib/views/file-patch-view.js
  lib/views/staging-view.js
  test/models/composite-list-selection.test.js
  test/models/file-patch-selection.test.js
  test/models/list-selection.test.js
  test/views/composite-list-selection.test.js
  test/views/list-selection.test.js
Labels: code-cleanup :wrench:

#1414 Rework PaneItem management
  lib/atom-items/issueish-pane-item.js
  lib/atom/pane-item.js
  lib/atom/uri-pattern.js
  lib/containers/pr-info-container.js
  lib/controllers/file-patch-controller.js
  lib/controllers/root-controller.js
  lib/github-package.js
  lib/helpers.js
  lib/views/git-timings-view.js
  lib/views/pane-item.js
  lib/views/panel.js
  lib/views/staging-view.js
  package.json
  test/atom/pane-item.test.js
  test/atom/uri-pattern.test.js
  test/controllers/root-controller.test.js
  test/pane-items/issueish-pane-item.test.js
  test/views/pane-item.test.js
Labels: code-cleanup :wrench:

#1426 Move Atom API bridge components to lib/atom
  lib/atom/atom-text-editor.js
  lib/atom/commands.js
  lib/atom/decoration.js
  lib/atom/dock-item.js
  lib/atom/octicon.js
  lib/atom/panel.js
  lib/atom/simple-tooltip.js
  lib/atom/status-bar.js
  lib/atom/tooltip.js
  lib/containers/issueish-pane-item-container.js
  lib/containers/issueish-tooltip-container.js
  lib/containers/pr-info-container.js
  lib/containers/pr-selection-by-branch-container.js
  lib/containers/pr-status-context-container.js
  lib/containers/pr-statuses-container.js
  lib/containers/timeline-items/commit-comment-container.js
  lib/containers/timeline-items/commit-container.js
  lib/containers/timeline-items/commits-container.js
  lib/containers/timeline-items/cross-referenced-event-container.js
  lib/containers/timeline-items/cross-referenced-events-container.js
  lib/containers/timeline-items/head-ref-force-pushed-event-container.js
  lib/containers/timeline-items/issue-comment-container.js
  lib/containers/timeline-items/merged-event-container.js
  lib/containers/user-mention-tooltip-container.js
  lib/controllers/conflict-controller.js
  lib/controllers/editor-conflict-controller.js
  lib/controllers/root-controller.js
  lib/controllers/status-bar-tile-controller.js
  lib/views/branch-menu-view.js
  lib/views/changed-files-count-view.js
  lib/views/clone-dialog.js
  lib/views/co-author-form.js
  lib/views/commit-view.js
  lib/views/credential-dialog.js
  lib/views/file-patch-view.js
  lib/views/git-timings-view.js
  lib/views/hunk-view.js
  lib/views/init-dialog.js
  lib/views/issueish-badge.js
  lib/views/issueish-timeline-view.js
  lib/views/open-issueish-dialog.js
  lib/views/push-pull-view.js
  lib/views/staging-view.js
  test/atom/commands.test.js
  test/atom/decoration.test.js
  test/atom/panel.test.js
  test/controllers/conflict-controller.test.js
Labels: code-cleanup :wrench:
