Repository atom/github, pull requests merged in 2018-06, with the labels that each got.

#1500 Revisit commit message processing
  lib/controllers/commit-controller.js
  lib/git-shell-out-strategy.js
  lib/helpers.js
  lib/models/repository.js
  test/controllers/commit-controller.test.js
  test/controllers/git-tab-controller.test.js
  test/git-strategies.test.js
Labels: work-in-progress

#1503 RFC for Issueish List View
  docs/rfcs/002-issueish-list.md
Labels: rfc

#1521 Dead code cleanup
  lib/multi-list-collection.js
  lib/multi-list.js
  test/multi-list-collection.test.js
  test/multi-list.test.js
Labels: code-cleanup :wrench:

#1551 Refactor IssueishPaneItemView
  lib/containers/issueish-pane-item-container.js
  lib/containers/pr-statuses-container.js
  lib/views/issueish-badge.js
  styles/_global.less
  styles/github-dotcom-markdown.less
  styles/issueish-badge.less
  styles/issueish-pane-item-view.less
  styles/issueish-tooltip.less
  styles/pr-pane-item.less
  styles/pr-statuses.less
Labels: code-cleanup :wrench:

#1547 Move git and github tab items to a PaneItem
  lib/atom/dock-item.js
  lib/atom/pane-item.js
  lib/controllers/git-tab-controller.js
  lib/controllers/github-tab-controller.js
  lib/controllers/root-controller.js
  lib/github-package.js
  lib/helpers.js
  lib/index.js
  lib/items/git-tab-item.js
  styles/git-tab-item.less
  styles/github-controller.less
  test/atom/pane-item.test.js
  test/controllers/root-controller.test.js
  test/fixtures/props/git-tab-props.js
  test/github-package.test.js
  test/integration/helpers.js
  test/integration/launch.test.js
  test/integration/open.test.js
  test/items/git-tab-item.test.js
Labels: code-cleanup :wrench:, work-in-progress
