Repository atom/github, pull requests merged in 2018-10, with the labels that each got.

#1706 RFC for Pull Request Review
  docs/rfcs/003-pull-request-review.md
Labels: documentation, rfc

#1726 Documentation on our component architecture
  docs/react-component-atlas.md
  docs/react-component-classification.md
Labels: documentation

#1702 Move "Undo Discard" button behind context menu
  lib/controllers/file-patch-controller.js
  lib/views/file-patch-view.js
  lib/views/staging-view.js
  menus/git.cson
  styles/staging-view.less
  test/controllers/file-patch-controller.test.js
  test/views/staging-view.test.js
Labels: documentation, metrics

#1735 Document the way we interact with git
  docs/git-interactions.md
Labels: documentation

#1744 Add some instrumentation
  lib/controllers/root-controller.js
  test/controllers/root-controller.test.js
Labels: metrics

#1746 Process proposal
  docs/core-team-process.md
Labels: documentation, work-in-progress
