Repository atom/github, pull requests merged in 2019-05, with the labels that each got.

#2107 Exclude deprecated fields from the fetched schema
  script/fetch-schema
Labels: graphql

#2095 Feature Request: Review author flow
  docs/feature-requests/006-pull-request-reviewer-flow.md
Labels: feature request

#2150 :arrow_up: react + react-dom
  package-lock.json
  package.json
Labels: dependencies
